name = "Example"
uuid = "7876af07-990d-54b4-ab0e-23690620f79a"
version = "0.5.5"

[weekdeps]
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[extensions]
StaticArraysCoreExt = "StaticArraysCore"

[compat]
StaticArraysCore = "1.4.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
